"""
=============================================================================
VULNERABLE JWT AUTHENTICATION API
=============================================================================
Person 1 — Vulnerable API + JWT Authentication

PURPOSE: Intentionally vulnerable Flask API demonstrating real-world JWT
         authentication bypass vulnerabilities.

VULNERABILITIES INCLUDED:
  1. alg:none — accepts tokens with no signature
  2. RS256 → HS256 confusion — accepts RS256 public key as HMAC secret
  3. Weak token verification — trusts algorithm in token header

DO NOT USE IN PRODUCTION — FOR EDUCATIONAL/CTF PURPOSES ONLY
=============================================================================
"""

import jwt
import json
import os
from flask import Flask, request, jsonify
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend
from functools import wraps
from datetime import datetime, timedelta

app = Flask(__name__)

# ─────────────────────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────────────────────

# HMAC secret used for HS256 tokens
# VULNERABILITY: weak, hardcoded secret (easily brute-forced)
HS256_SECRET = "supersecretkey123"

# Paths to RSA keys (generated by generate_keys.py)
PRIVATE_KEY_PATH = os.path.join(os.path.dirname(__file__), "keys", "private.pem")
PUBLIC_KEY_PATH  = os.path.join(os.path.dirname(__file__), "keys", "public.pem")

# Load RSA keys at startup
with open(PRIVATE_KEY_PATH, "rb") as f:
    PRIVATE_KEY = serialization.load_pem_private_key(f.read(), password=None, backend=default_backend())

with open(PUBLIC_KEY_PATH, "rb") as f:
    PUBLIC_KEY_PEM = f.read()  # raw PEM bytes
    PUBLIC_KEY     = serialization.load_pem_public_key(PUBLIC_KEY_PEM, backend=default_backend())

# Simulated user database
USERS = {
    "alice": {"password": "password123", "role": "user"},
    "bob":   {"password": "letmein",     "role": "user"},
    "admin": {"password": "adm1n$ecret", "role": "admin"},
}

# ─────────────────────────────────────────────────────────────
# VULNERABLE JWT VERIFICATION
# ─────────────────────────────────────────────────────────────

def vulnerable_decode_jwt(token: str) -> dict | None:
    """
    VULNERABILITY: This function reads the 'alg' field from the JWT header
    WITHOUT verifying it against an allowed algorithm list.

    Attack surface:
      - alg=none   → signature skipped entirely
      - alg=HS256  → attacker uses the PUBLIC key as HMAC secret (RS256→HS256 confusion)
      - alg=RS256  → verified normally

    A secure implementation MUST specify algorithms= explicitly and NEVER
    trust the header's alg claim.
    """
    try:
        # Decode header without verification to see which alg was used
        header = jwt.get_unverified_header(token)
        alg    = header.get("alg", "").upper()

        if alg == "NONE":
            # ❌ VULNERABILITY 1: alg=none bypass
            # PyJWT by default rejects none, but we're calling it with options=
            # that disable signature verification — simulating a broken implementation.
            payload = jwt.decode(
                token,
                options={
                    "verify_signature": False,  # ← DANGEROUS
                    "verify_exp": True,
                },
                algorithms=["none"],
            )
            return payload

        elif alg == "HS256":
            # ❌ VULNERABILITY 2: RS256→HS256 confusion
            # A vulnerable implementation uses the PUBLIC key as the HMAC secret.
            # We simulate this by manually verifying the HMAC rather than relying
            # on PyJWT (which added a safeguard against this exact pattern in >= 2.4).
            #
            # Real-world vulnerable libraries (node-jsonwebtoken < 4.2.2, python-jose < 3.x)
            # simply passed public_key_pem directly as the HS256 secret.
            import hmac as _hmac
            import hashlib as _hashlib

            parts = token.split(".")
            if len(parts) != 3:
                return None

            signing_input = f"{parts[0]}.{parts[1]}".encode("utf-8")
            import base64 as _base64

            def _b64d(s):
                s += "=" * (4 - len(s) % 4)
                return _base64.urlsafe_b64decode(s)

            expected_sig = _hmac.new(
                key=PUBLIC_KEY_PEM,          # ← public key as HMAC secret (the vulnerability!)
                msg=signing_input,
                digestmod=_hashlib.sha256,
            ).digest()

            provided_sig = _b64d(parts[2])

            if not _hmac.compare_digest(expected_sig, provided_sig):
                return None

            # Signature matched — decode payload (this is what the vulnerable server does)
            payload_json = _b64d(parts[1])
            import json as _json
            return _json.loads(payload_json)

        elif alg == "RS256":
            # Legitimate RS256 verification (correct behavior)
            payload = jwt.decode(
                token,
                key=PUBLIC_KEY,
                algorithms=["RS256"],
            )
            return payload

        else:
            return None

    except jwt.ExpiredSignatureError:
        return None
    except jwt.InvalidTokenError:
        return None


# ─────────────────────────────────────────────────────────────
# DECORATOR — Require Valid JWT
# ─────────────────────────────────────────────────────────────

def require_jwt(f):
    """Middleware decorator that enforces JWT authentication."""
    @wraps(f)
    def decorated(*args, **kwargs):
        auth_header = request.headers.get("Authorization", "")
        if not auth_header.startswith("Bearer "):
            return jsonify({"error": "Missing or malformed Authorization header"}), 401

        token   = auth_header.split(" ", 1)[1]
        payload = vulnerable_decode_jwt(token)

        if payload is None:
            return jsonify({"error": "Invalid or expired token"}), 401

        request.jwt_payload = payload
        return f(*args, **kwargs)

    return decorated


def require_admin(f):
    """Middleware decorator that enforces admin role."""
    @wraps(f)
    @require_jwt
    def decorated(*args, **kwargs):
        role = request.jwt_payload.get("role", "user")
        if role != "admin":
            return jsonify({"error": "Admin access required", "your_role": role}), 403
        return f(*args, **kwargs)

    return decorated


# ─────────────────────────────────────────────────────────────
# ROUTES
# ─────────────────────────────────────────────────────────────

@app.route("/", methods=["GET"])
def index():
    """Root endpoint — shows available routes."""
    return jsonify({
        "service": "JWT Auth Bypass Lab",
        "version": "1.0.0",
        "endpoints": {
            "GET  /":           "This help message",
            "POST /login":      "Get a JWT token (HS256 or RS256)",
            "GET  /profile":    "View your profile (requires JWT)",
            "GET  /admin":      "Admin-only endpoint (requires admin role)",
            "GET  /public-key": "Fetch the RSA public key (used in attacks)",
        },
        "note": "This API is intentionally vulnerable — for educational use only.",
    })


@app.route("/login", methods=["POST"])
def login():
    """
    Login endpoint — issues JWT tokens.

    POST body (JSON):
      { "username": "alice", "password": "password123", "alg": "HS256" }

    The 'alg' field lets the client choose HS256 or RS256.
    VULNERABILITY: In production, the server should always decide the algorithm.
    """
    data = request.get_json(silent=True) or {}

    username = data.get("username", "")
    password = data.get("password", "")
    alg      = data.get("alg", "HS256").upper()

    # Check credentials
    user = USERS.get(username)
    if not user or user["password"] != password:
        return jsonify({"error": "Invalid credentials"}), 401

    # Build JWT payload
    now     = datetime.utcnow()
    payload = {
        "sub":      username,
        "role":     user["role"],
        "iat":      now,
        "exp":      now + timedelta(hours=1),
        "iss":      "jwt-lab",
    }

    # Issue token with requested algorithm
    if alg == "RS256":
        token = jwt.encode(payload, PRIVATE_KEY, algorithm="RS256")
    else:
        # Default: HS256
        token = jwt.encode(payload, HS256_SECRET, algorithm="HS256")

    return jsonify({
        "token":     token,
        "algorithm": alg,
        "username":  username,
        "role":      user["role"],
        "expires_in": "1 hour",
    })


@app.route("/profile", methods=["GET"])
@require_jwt
def profile():
    """
    Protected profile endpoint.
    Requires a valid JWT. Returns the decoded payload.
    """
    payload = request.jwt_payload
    return jsonify({
        "message":  f"Hello, {payload.get('sub', 'unknown')}!",
        "username": payload.get("sub"),
        "role":     payload.get("role"),
        "issued_at":   str(payload.get("iat")),
        "expires_at":  str(payload.get("exp")),
    })


@app.route("/admin", methods=["GET"])
@require_admin
def admin():
    """
    Admin-only endpoint.
    Returns the CTF flag if the request carries a valid admin JWT.

    This is the target for the attack demonstrations.
    """
    payload = request.jwt_payload
    return jsonify({
        "message":   "🔓 ADMIN ACCESS GRANTED",
        "flag":      "FLAG{jwt_bypass_success}",
        "username":  payload.get("sub"),
        "role":      payload.get("role"),
        "warning":   "You exploited a JWT vulnerability — patch your code!",
        "cve_refs": [
            "CVE-2015-9235 (alg:none)",
            "CVE-2016-5431 (RS256→HS256 confusion)",
        ],
    })


@app.route("/public-key", methods=["GET"])
def public_key():
    """
    Exposes the RSA public key.

    ATTACKER NOTE: This endpoint is the starting point for the RS256→HS256
    confusion attack. The attacker fetches this key and uses it as an HMAC
    secret to forge tokens.

    In real systems, public keys are often in JWKS endpoints or certificates
    that are publicly accessible by design — making this attack realistic.
    """
    return jsonify({
        "public_key":  PUBLIC_KEY_PEM.decode("utf-8"),
        "algorithm":   "RS256",
        "key_type":    "RSA-2048",
        "note":        "Fetching this key is the first step in the confusion attack.",
    })


# ─────────────────────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("  JWT Auth Bypass Lab — Vulnerable API")
    print("  Running on http://0.0.0.0:5000")
    print("  DO NOT USE IN PRODUCTION")
    print("=" * 60)
    app.run(host="0.0.0.0", port=5000, debug=True)
